# ===============================================
# CONFIGURACIÓN DE CONEXIÓN A ORACLE CLOUD
# ===============================================

# Apunta a la carpeta wallet en la ruta absoluta del contenedor Docker
spring.datasource.url=jdbc:oracle:thin:@proyectointegrador_medium?TNS_ADMIN=/app/wallet

# Driver JDBC de Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Credenciales de acceso
spring.datasource.username=ADMIN
spring.datasource.password=Integradora1

# ===============================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
